service: stockquote-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  stage: dev
  profile: default
  environment:
    ALPHA_VANTAGE_API_KEY: ${env:ALPHA_VANTAGE_API_KEY}

functions:
  app:
    handler: src/index.handler
    events:
      - httpApi: '*'

  stockquote:
    handler: src/index.handler
    events:
      - http:
          path: soap/stockquote
          method: post
          cors: true

plugins:
  - serverless-esbuild

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10
